### ISSUE TITLE
Backfill scripts failing

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/stix2arango#26]
```
python3 utilities/arango_cti_processor/insert_archive_attack_enterprise.py \
	--database ctibutler
```

After the scripts have imported 8/9 old versions, errors like the below start to occir

```
[2024-10-25 - 15:40:02] INFO - Reading vertex from file /Users/dgreenwood/Documents/repos/dogesec/stix2arango/cti_knowledge_base_store/mitre-attack-enterprise/enterprise-attack-11_2.json now
100%|████████████████████████████████| 17672/17672 [00:00<00:00, 212672.05it/s]
[2024-10-25 - 15:40:02] INFO - Inserting objects into database. Total objects: 1895
[2024-10-25 - 15:40:02] INFO - removed 0 duplicates from imported objects.
  0%|                                         | 2/1895 [00:00<08:14,  3.83it/s]
[2024-10-25 - 15:40:03] INFO - Updating _is_latest for 1895 newly inserted items
  0%|                                         | 4/1895 [00:02<17:04,  1.85it/s]
[2024-10-25 - 15:40:05] INFO - Mapping relationships now -> 
[2024-10-25 - 15:40:05] INFO - Mapping Prebuilt Relationship Objects -> 
100%|█████████████████████████████████| 17672/17672 [00:00<00:00, 62107.01it/s]
[2024-10-25 - 15:40:05] INFO - Inserting relationship into database. Total objects: 15777
[2024-10-25 - 15:40:05] INFO - removed 0 duplicates from imported objects.
  0%|                                     | 14/15777 [00:10<3:23:33,  1.29it/s]
[2024-10-25 - 15:40:16] INFO - Updating _is_latest for 15777 newly inserted items
  0%|                                     | 32/15777 [00:50<6:57:27,  1.59s/it]
[2024-10-25 - 15:41:07] INFO - Creating new embedded relationships using _refs and _ref
100%|██████████████████████████████████| 17672/17672 [00:02<00:00, 6535.24it/s]
[2024-10-25 - 15:41:10] INFO - Inserting embedded relationship into database. Total objects: 70796
[2024-10-25 - 15:41:11] INFO - removed 0 duplicates from imported objects.
  0%|                                    | 59/70796 [00:42<14:14:25,  1.38it/s]
[2024-10-25 - 15:41:53] INFO - Updating _is_latest for 70796 newly inserted items
  0%|                                   | 142/70796 [03:03<25:19:18,  1.29s/it]
Traceback (most recent call last):
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=8529): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dgreenwood/Documents/repos/dogesec/stix2arango/stix2arango.py", line 5, in <module>
    main()
  File "/Users/dgreenwood/Documents/repos/dogesec/stix2arango/stix2arango/__main__.py", line 24, in main
    stix_obj.run()
  File "/Users/dgreenwood/Documents/repos/dogesec/stix2arango/stix2arango/stix2arango/stix2arango.py", line 208, in run
    self.arango.update_is_latest_for_embedded_refs(inserted_object_ids+inserted_relationship_ids, self.core_collection_edge)
  File "/Users/dgreenwood/Documents/repos/dogesec/stix2arango/stix2arango/services/arangodb_service.py", line 227, in update_is_latest_for_embedded_refs
    return self.execute_raw_query(query, bind_vars={
  File "/Users/dgreenwood/Documents/repos/dogesec/stix2arango/stix2arango/services/arangodb_service.py", line 102, in execute_raw_query
    cursor = self.db.aql.execute(query, bind_vars=bind_vars, **kwargs)
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/arango/aql.py", line 453, in execute
    return self._execute(request, response_handler)
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/arango/api.py", line 74, in _execute
    return self._executor.execute(request, response_handler)
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/arango/executor.py", line 65, in execute
    resp = self._conn.send_request(request)
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/arango/connection.py", line 281, in send_request
    return self.process_request(host_index, request, auth=self._auth)
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/arango/connection.py", line 138, in process_request
    resp = self._http.send_request(
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/arango/http.py", line 223, in send_request
    response = session.request(
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/dgreenwood/.pyenv/versions/3.10.9/lib/python3.10/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8529): Read timed out. (read timeout=60)
Failed to process /Users/dgreenwood/Documents/repos/dogesec/stix2arango/cti_knowledge_base_store/mitre-attack-enterprise/enterprise-attack-11_2.json: Command '['python3', '/Users/dgreenwood/Documents/repos/dogesec/stix2arango/stix2arango.py', '--file', '/Users/dgreenwood/Documents/repos/dogesec/stix2arango/cti_knowledge_base_store/mitre-attack-enterprise/enterprise-attack-11_2.json', '--database', 'ctibutler', '--collection', 'mitre_attack_enterprise', '--stix2arango_note', 'v11.2', '--ignore_embedded_relationships', 'false']' returned non-zero exit status 1
```

**Comment by himynamesdave** [comment]
@fqrious i thought is might have something to do with that.

but why does it start to fail on version 9 specifically?

the numbers of embedded relationships are about the same in each version (although do increase ever-so-slightly with each, but not enough that I'd expect is to lead to a failure)

**Comment by fqrious** [comment]
Well, because the database is expanding as you upload more and more versions and the number of scans continue to increase. also, it was not failing the query was just taking too long to process and requests library has a default timeout.

**Comment by himynamesdave** [comment]
> Well, because the database is expanding as you upload more and more versions and the number of scans continue to increase.

I don't understand this point though.

Lets me explain

Import 1: 1000 objects, 5k embedded rels
Import 2: 1002 objects, 6k embedded rels (age out 1000 objects, 5k embedded rels from import 2)
Import 3 1004 objects, 7k embedded rels (age out 1002 objects, 6k embedded rels from import 3)

and so on

If it failed at import 2 I could understand this argument

but the compounding effects of new imports between 1 and 9 is not that different (in ATT&CK example)

**Comment by fqrious** [comment]
Import 1, 1000 objects iterated
Import 2: 1002+1000 objects iterated
Import 3: 1004+1002+1000 objects iterated 

And so on

**Comment by himynamesdave** [comment]
But this is what I don't understand. Why do the previous versions need updating

Import 3: 7k+6k+5k objects processed

can you describe step by step what is happening here.

I thought we only considered _is_latest = new, and age them out accordingly. So _is_latest=false are ignore (in this example 5k), 7k is new objects, 6k is latest objects, about to be changed

**Comment by fqrious** [comment]
it's not so simple, the spec not only expects that we deprecate relationships that attach to object, but relationships that attach to the relationships that attach to the objects... unless we're doing it one request per object (simple, 100x as slow).
